### ISSUE TITLE
Misplaced letters are highlighted even when already placed

### ISSUE THREAD

**Issue by nate-anderson** [AshishShenoy/wordle#2]
If a guess contains the same letter twice, and one instance of the letter is in the correct place, the other letter should _only_ be highlighted yellow if that letter does, in fact, appear twice in the target word.

For example, if the target word is "SMILY" and a user guesses "SKILL", the first L should be highlighted green and the second should not be highlighted at all.

Attached is an example from Powerlanguage's implementation demonstrating specified behavior, and a screenshot of the bug in this program. Notice the first "T" in "TRIST" is not highlighted yellow.

![Screenshot_20220202-170658_Firefox Beta](https://user-images.githubusercontent.com/33207577/152264243-1412dbc4-2642-4cf6-8e27-93d91e438b10.jpg)

![image](https://user-images.githubusercontent.com/33207577/152264394-fc66ca6e-b267-4953-b8a8-605c4fa7d09a.png)

**Comment by AshishShenoy** [comment]
You're right. I knew there was an issue but couldn't figure out what it was.
I guess the logic needs two rounds of comparisons between `guess_word` and `selected_word`, one to mark all green characters and then one to mark yellow characters if the corresponding index hasn't already been matched green.

 You interested in doing the pull request for this issue?
